os: linux
sudo: required
language:
- minimal
services:
- docker

jobs:
  include:
  - name: "build"
    script:
        - cmake -H. -B_build 
        - cmake --build _build
notifications:
    email: false
